---
layout: post
title: AutoCADでブロック名称を変更したい
date: 2018-04-13 08:58:36
categories: vba autocad
---
<p>お世話になっております。<br>
AutoCAD2008 VBAについての質問です。<br>
現存するブロックの名称を変更したいのですが、方法がわかりません。<br>
現状、下記のようにプログラムを作成しています。</p>

```
Dim objEntity As AcadEntity
For Each objEntity In ThisDrawing.ModelSpace

  '取り出された図形のAutoCADクラス名により対象か否かを判定
  If objEntity.ObjectName = "AcDbBlockReference" Then
    For iii = 1 To 1000
      ii = 1000 - iii + 1
      If Val(Right(objEntity.Name, 3)) = ii Then
        charln = Len(Str(Val(Right(Str(ii), 3)) + 1))
        juki_edaban = Right("000" + Right(Str(ii + 1), charln - 1), 3)
        objEntity.Name = juki_edaban ←（ここで以下のエラーが出ます）
    Exit For
  End If
Next

End If

Next
```

<p>（エラー内容）<br>
実行時エラー　'-2145386476 (80200014X)'<br>
キーが見つかりません</p>

<p>なにか方法があればご教授いただけないでしょうか？<br>
よろしくお願いします。</p>
